# Generated by Django 5.2 on 2025-04-09 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('finished', 'Finished')], default='created', max_length=20)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('biceps_circumference', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
